### ISSUE TITLE
Noto fonts missing character

### ISSUE THREAD

**Issue by KaushickSArgekar** [rbcprolabs/icon_font_generator#13]
Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts

**Comment by SergeShkurko** [comment]
@KaushickSArgekar you added font at pubspec? (from readme instruction)
![image](https://user-images.githubusercontent.com/18213789/116592368-99db3c80-a928-11eb-9724-b52a07ce24ca.png)

also need run flutter clean and restart app

**Comment by KaushickSArgekar** [comment]
Yes, @SergeShkurko  I have added the font family in pubspec.yamil.

flutter:
  fonts:
    - family: AppIcons
      fonts:
        - asset: lib/assets/icons/app_icons.ttf

**Comment by KaushickSArgekar** [comment]
I am using the icons in the package and then exporting them in a project.

**Comment by SergeShkurko** [comment]
@KaushickSArgekar 
> Could not find a set of Noto 

here the font is named differently

**Comment by infinito84** [comment]
Works from restart the flutter run process

**Comment by andreypUP** [comment]
I solved the bug by setting the correct font family in the `pubspec.yaml` file. 
Steps: 
1. Go to the generated icon font file, in my case the name is `my_icons.dart`
![image](https://github.com/ScerIO/icon_font_generator/assets/139485966/0138b071-3fcd-4188-b006-0acb116b6ff2)
2. Copy the iconFontFamily value 
3. Paste the value to the font family config 
![image](https://github.com/ScerIO/icon_font_generator/assets/139485966/f889088b-643e-4d37-9aa0-62a99368b493)

Better/Organized way: If you are using `icon_font.yaml` to generate the custom fonts, follow these steps: 
1. Create icon_font.yaml file
```
icon_font:
  input_svg_dir: "assets/svg/"
  output_font_file: "fonts/my_icons_font.otf"
  
  output_class_file: "lib/my_icons.dart"
  class_name: "MyIcons"
  package: my_font_package     // remove this if you don't know how to set the package in pubspec.yaml
  format: true

  font_name: "My Icons"
  normalize: true
  ignore_shapes: true

  recursive: true
  verbose: false
```
  
  **Note:** I removed the package config in my case
2.  Run this command in CLI: 
`dart run icon_font_generator:generator --config-file=icon_font.yaml -r`
Copy the iconFontFamily value from the generated dart file. 

3. Add dependencies to `pubspec.yaml` and use the iconFontFamily value correctly ( 'My Icons' in this case)
example: 
```
fonts:
    - family: My Icons
      fonts:
        - asset: fonts/my_icons_font.otf
```


If this does not work, please comment again. Thanks!
