### ISSUE TITLE
Could not find bin/icon_font_generator.dart in package icon_font_generator.

### ISSUE THREAD

**Issue by GiorgiaDip** [rbcprolabs/icon_font_generator#42]
Hello, I'm using icon_font_generator to add custom svg icon to my application. After completing each configuration step I noticed that my icons are some random emoji  with an iphone-like style. 

When trying to run this command `flutter pub run icon_font_generator ` I have this error: **Could not find bin/icon_font_generator.dart in package icon_font_generator.**

Here are the steps I did:

1. added the package to dev_dependencies (icon_font_generator: ^4.0.0)
2. run `flutter pub global activate icon_font_generator  `
3. run `flutter pub run icon_font_generator `

Also, from the documentations, I saw there is a command called "generator" that actually builds up something but I still see my svg icons as emojes. Please if anyone encountered help me solve it

Also providing my configuration in the `.yaml `file:

```
icon_font:
  input_svg_dir: "assets/svg/"
  output_font_file: "fonts/app_icons_font.otf"

  output_class_file: "lib/src/core/theme/app_icons.dart"
  class_name: "AppIcons"
  format: true

  font_name: "App Icons"
  normalize: true
  ignore_shapes: false

  recursive: false
  verbose: false

```
