### ISSUE TITLE
Icon generate successfully but shows wrong icon

### ISSUE THREAD

**Issue by abdullah-cse** [rbcprolabs/icon_font_generator#43]
Thanks for this handy package.
It seems icon generate correctly.
Here is a screenshot, when i am writing code the preview shows **Home** icon

![iconExpected](https://github.com/ScerIO/icon_font_generator/assets/58176575/b3821544-7034-4137-9259-20dce0533cf9)

But when i build software it shows wrong icon. Here **Home** icon become a **Chinese symbol**

![image](https://github.com/ScerIO/icon_font_generator/assets/58176575/1dbdb3cd-48bc-47b3-912d-7d65de442e02)

Is there any solution?

**Comment by abdullah-cse** [comment]
Problem solved!
Removing `  package: my_font_package` solved the problem.
```yaml
icon_font:
  input_svg_dir: "assets/svg/"
  output_font_file: "fonts/my_icons_font.otf"
  output_class_file: "lib/my_icons.dart"
  class_name: "MyIcons"
  # package: my_font_package   //Removing this line solved problem
  format: true
  font_name: "My Icons"
  normalize: true
  ignore_shapes: true
  recursive: true
  verbose: true
```
